In [6]:
class Employee:
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    @classmethod
    def average_salary(cls, employees):
        total_salary = sum(emp.salary for emp in employees)
        return round(total_salary / len(employees), 2) if employees else 0

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

emp1 = Employee("santhosh", "katta", 100000, "engineer")
emp2 = Employee("dinesh", "kumar", 60000, "HR")
fulltime_emp1 = FulltimeEmployee("raju", "dev", 70000, "IT")

employees = [emp1, emp2, fulltime_emp1]

print(f"Total number of employees: {Employee.employee_count}")
print(f"Average salary of employees: {Employee.average_salary(employees)}")


Total number of employees: 3
Average salary of employees: 76666.67


In [8]:
import numpy as np

vector = np.random.uniform(1, 20, 20)
matrix = vector.reshape(4, 5)
matrix[np.arange(matrix.shape[0]), matrix.argmax(axis=1)] = 0

print("Modified Matrix:\n", matrix)


Modified Matrix:
 [[ 7.18587016  6.34807352  3.56818704  0.          2.82862174]
 [16.63665315  0.          1.41507093 15.24933691  9.48978593]
 [ 3.74845189 10.58591621 17.27981452  0.         12.19657969]
 [11.38750776  5.7796866   0.          7.3268388   5.37638867]]


this is an [icp2 video link](https://drive.google.com/file/d/10L8XVlB8cM2lYbODv_QQENR4VMeFDEs0/view?usp=sharing).